### ISSUE TITLE
Is there a GeoKey for epsg number or proj4string?

### ISSUE THREAD

**Issue by ramespada** [OSGeo/libgeotiff#108]
HI,

(Sorry this is not an issue but a question..)

I want to use PROJ to re-project some .tiff layers, And there are so many geoKeys to define the projection. wouldn't be enough just to give the epsg number or a proj4 string that PROJ could deal with it? 

Regards and thanks for all your work!

**Comment by rouault** [comment]
> wouldn't be enough just to give the epsg number or a proj4 string that PROJ could deal with it?

yes, the ProjectedCSTypeGeoKey key is for that purpose. Cf https://docs.ogc.org/is/19-008r4/19-008r4.html#_requirements_class_projectedcrsgeokey and 
```
$ listgeo byte.tif
Geotiff_Information:
   Version: 1
   Key_Revision: 1.0
   Tagged_Information:
      ModelTiepointTag (2,3):
         0                 0                 0                
         440720            3751320           0                
      ModelPixelScaleTag (1,3):
         60                60                0                
      End_Of_Tags.
   Keyed_Information:
      GTModelTypeGeoKey (Short,1): ModelTypeProjected
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      GTCitationGeoKey (Ascii,21): "NAD27 / UTM zone 11N"
      GeogCitationGeoKey (Ascii,6): "NAD27"
      GeogAngularUnitsGeoKey (Short,1): Angular_Degree
      ProjectedCSTypeGeoKey (Short,1): PCS_NAD27_UTM_zone_11N
      ProjLinearUnitsGeoKey (Short,1): Linear_Meter
      End_Of_Keys.
   End_Of_Geotiff.
```
