### ISSUE TITLE
pre-compiled geotifcp.exe

### ISSUE THREAD

**Issue by dwilbourn618** [OSGeo/libgeotiff#109]
Would it be possible to include a pre-compiled geotifcp.exe for those of that don't have access the Visual Studio and just want to use the exe to create geotifs?

**Comment by thbeu** [comment]
`vcpkg intall libgeotiff[tools]` produced the desired binaries: [tools.zip](https://github.com/OSGeo/libgeotiff/files/14515791/tools.zip)

**Comment by dwilbourn618** [comment]
Thanks, but would it not be better and more useful if the binaries were a normal part of the main github page so people can download and use them without having to get access to Visual C compilers?

**Comment by rouault** [comment]
This project has not the manpower to provide ready made binaries directly
