### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by dwilbourn618** [OSGeo/libgeotiff#110]
It would appear libgeotiff does not support transparency in TIFF files when converting them to a GeoTiff. I have tested creating a GeoTiff from a Tiff both with and without a transparent background and QGIS will happily read the Geotiff with a solid background but cannot read the one with a transparent background.

**Comment by rouault** [comment]
transparency is out of the scope of geotiff itself. It is more a TIFF or GDAL concept. geotiff is orthogonal to that
