### ISSUE TITLE
1.5.1 does not build in separate dir from source

### ISSUE THREAD

**Issue by matzeri** [OSGeo/libgeotiff#28]
The default build on Cygwin package tool is to have separate directory for source and build and 1.5.1 does not support it.

The attached patch allows to build on a separate directory from source, amend the test output to avoid spurious errors and add the needed "undefined" for cygwin and other similar system.

[libgeotiff-1.5.1-1.src.patch.gz](https://github.com/OSGeo/libgeotiff/files/4163296/libgeotiff-1.5.1-1.src.patch.gz)

after that, the test output is just due to minor nomenclature difference on my system

```
--- testlistgeo_out     2020-02-06 05:54:08.880564500 +0100
+++ /cygdrive/d/cyg_pub/devel/libgeotiff/libgeotiff-1.5.1-1.x86_64/src/libgeotiff-1.5.1/test/testlistgeo_out.dist       2019-03-25 16:31:36.000000000 +0100
@@ -1697,11 +1697,11 @@
    Keyed_Information:
       GTModelTypeGeoKey (Short,1): ModelTypeProjected
       GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
-      ProjectedCSTypeGeoKey (Short,1): Code-3035 (ETRS89-extended / LAEA Europe)
+      ProjectedCSTypeGeoKey (Short,1): Code-3035 (ETRS89 / LAEA Europe)
       End_Of_Keys.
    End_Of_Geotiff.

-PCS = 3035 (ETRS89-extended / LAEA Europe)
+PCS = 3035 (ETRS89 / LAEA Europe)
 Projection = 19986 (Europe Equal Area 2001)
 Projection Method: CT_LambertAzimEqualArea
    ProjCenterLatGeoKey: 52.000000 ( 52d 0' 0.00"N)
```

**Comment by rouault** [comment]
> The attached patch

Please provide it as a pull request

> the test output is just due to minor nomenclature difference on my system

Yes due to differences in the EPSG database depending on the PROJ version. Is in principle fixed per https://github.com/OSGeo/libgeotiff/commit/678ffd97db2d63cf6856428bea65a93e069f812f
