### ISSUE TITLE
gdal nodata

### ISSUE THREAD

**Issue by ggshome** [OSGeo/libgeotiff#43]
Can somebody explain to me why the latest release no longer supports the gdal nodata tag?

**Comment by rouault** [comment]
libgeotiff has never explicitly supported the gdal nodata tag ? What exactly did you do and what would have changed between libgeotiff releases ?

**Comment by ggshome** [comment]
Thanks for the quick response. Nothing special. I was porting some old code to 64bit. Long time ago I build libgeotiff and have used the nodata tag since. I decided to just take the binaries this time and noticed the "unknown tag" warning. So I downloaded the latest release of libgeotiff just to find out that the nodata tag was not present in xtiffio. I added it again so it works for me but I was just curious why it was removed. Judging by your response I must have used some old sources in the past that did include the nodata tag as I myself never added it.  
I like the explicit definition of nodata instead of relying on private definitions and always wandered why it is is not standardized
