### ISSUE TITLE
Random Assertion error

### ISSUE THREAD

**Issue by nicgar20** [OSGeo/libgeotiff#44]
Hi, 

I am working on a project to build a dataset by vectorizing small portions of some rasters, doing calculations over them and delivering a pickle file. I have been using the multiprocessing library from python and it works in random ways, and I mean random not by having an error linked to an specific datapoint.

This message appears randomly and it leads to an slow deadlock of my multiprocessing pool (it could appear between 3 to 6 times when processing 700k datapoints):
```python /tmp/build/80754af9/geotiff_1590596112627/work/geo_normalize.c:1456: GTIFGetProjTRFInfoEx: Assertion `pszMethodCode' failed.```
If im lucky enough that the error does not pop (it happens with the same dataset) the code will execute completely

for me it is odd that the ``` `pszMethodCode' ``` is between different quotation marks

I use anaconda and tried on python 3.7 and 3.8 environments, my main libraries are geopandas, shapely and rasterio

**Comment by rouault** [comment]
OK so if you rasterio, you use GDAL underneath. I believe this has been fixed in GDAL 3.1.3 as in the comment mentionned https://github.com/OSGeo/gdal/issues/3069#issuecomment-709566062

**Comment by nicgar20** [comment]
Thank you very much for your quick response. This solved my problems perfectly.
