### ISSUE TITLE
Feature request: Support TIFF tags 42112 (0xa480) and 42113 (0xa481)

### ISSUE THREAD

**Issue by twogood** [OSGeo/libgeotiff#56]
Now these are reported as:

TIFFReadDirectory: Warning, Unknown field with tag 42112 (0xa480) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 42113 (0xa481) encountered.

These are GDAL_METADATA and GDAL_NODATA according to:

https://www.awaresystems.be/imaging/tiff/tifftags/gdal_metadata.html

https://www.awaresystems.be/imaging/tiff/tifftags/gdal_nodata.html

I use  geotiff 1.5.1-2 on Ubuntu 20.04.2 LTS.

**Comment by rouault** [comment]
Those are defined in GDAL. If we wanted to move them down to the stack, libtiff itself would probably be a better host than libgeotiff. Actually in very recent libtiff releases, they are partially declared in it, but only for TIFFPrintDirectory(). It might be a bit tricky to move them and avoid the risk of redefinition between GDAL and libtiff
