### ISSUE TITLE
Issue building with Visual Studio 2019

### ISSUE THREAD

**Issue by EramarkMedia** [OSGeo/libgeotiff#58]
Good day.

Since i have been unable to locate version 2017 of Visual Studio for download anymore
I had to grab 2019 Community edition instead.

Having issues with compiling though, and wondering if this is due to the lack of defining in appveyor.yml?

# VS 2015
  - VS_VERSION: Visual Studio 14
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    platform: x86

# VS 2017
  - VS_VERSION: Visual Studio 15
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    
    Been on Linux for ages, and not really familiar with Visual Studio, neither do i have much experience with CMake to be honest, so i am quite lost, with trying to build on/for Windows.

**Comment by rouault** [comment]
This doesn't sound like a defect in libgeotiff, rather than a general build issue. Closing as such
