### ISSUE TITLE
Windows compilation gives error

### ISSUE THREAD

**Issue by Dave6954** [OSGeo/libgeotiff#59]
Im getting a few errors and not sure if the build notes a clear enough.

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:\Users\DAVID\Source\Repos\libgeotiff\libgeotiff\CMakeLists.txt:133 (MESSAGE):
  Failed to detect PROJ >= 6	GeoTIFF	C:\Users\DAVID\Source\Repos\libgeotiff\libgeotiff\CMakeLists.txt	133	

This occurs after installing PROJ.

Also after running 

_C:\Users\DAVID\source\repos\libgeotiff\libgeotiff\build>cmake -G "Visual Studio 16 2019" .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release  -DCMAKE_C_FLAGS="/WX" -DCMAKE_CXX_FLAGS="/WX"  -DCMAKE_INSTALL_PREFIX="C:/Users/DAVID/source/repos/libgeotiff/libgeotiff/build/install" -DPROJ_INCLUDE_DIR="C:/Users/DAVID/source/repos/libgeotiff/libgeotiff/build/install/include" -DPROJ_LIBRARY="C:/Users/DAVID/source/repos/libgeotiff/libgeotiff/build/install/lib/proj.lib" -DCMAKE_TOOLCHAIN_FILE=C:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake_

I get the error:

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
CMake Deprecation Warning at CMakeLists.txt:15 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at CMakeLists.txt:58 (cmake_policy):
  The OLD behavior for policy CMP0022 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at CMakeLists.txt:59 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Found PROJ: C:/Users/DAVID/source/repos/libgeotiff/libgeotiff/build/install/lib/proj.lib
CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find TIFF (missing: TIFF_LIBRARY TIFF_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindTIFF.cmake:124 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  CMakeLists.txt:171 (FIND_PACKAGE)

CMake Warning (dev) in C:/Program Files/CMake/share/cmake-3.21/Modules/FindTIFF.cmake:
  Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
  and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  The included script

    C:/Program Files/CMake/share/cmake-3.21/Modules/FindTIFF.cmake

  affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
  compatibility, so the effects are applied to the including context.
Call Stack (most recent call first):
  C:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  CMakeLists.txt:171 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "C:/Users/DAVID/source/repos/libgeotiff/libgeotiff/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/DAVID/source/repos/libgeotiff/libgeotiff/build/CMakeFiles/CMakeError.log".

**Comment by Dave6954** [comment]
@mloskot thanks for the reply, but i've installed PROJ and LibTIFF so im not sure where im going wrong

**Comment by Dave6954** [comment]
@mloskot thanks for this. I will try and work through your suggestions. I am new to VS and understanding more about the repo contents. Can the appveyor file get run as a script to run the whole build? How is that acheived?

**Comment by Dave6954** [comment]
when parsing vcpkg install tiff:"%platform%"-windows
i get the error:
<unknown>:1:6: error: expected triplet name (must be lowercase, digits, '-')
   on expression: tiff:%platform%-windows

**Comment by rouault** [comment]
Closing as a very likely usage issue rather than an issue in libgeotiff
