### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by jdefrancesco** [OSGeo/libgeotiff#66]
I have found an Out-Of-Bound Read; potential vulnerabilities. Do you have somewhere else you wish them to be reported for fixing?

**Comment by rouault** [comment]
here is fine

**Comment by jdefrancesco** [comment]
Will do.. 
![Screen Shot 2022-02-23 at 2 01 52 PM](https://user-images.githubusercontent.com/782408/155389161-b2c4bf30-7193-43fd-aa64-3afe178b66de.png)

Seems you have an off by one OOB read. You can see I can control the values of `sptr` which we read from on line 229 of `geo_print.c` If you wan't I can send you over the crash file.

**Comment by rouault** [comment]
> `` If you wan't I can send you over the crash file.

please attach it here
