### ISSUE TITLE
License cleanup?

### ISSUE THREAD

**Issue by schwehr** [OSGeo/libgeotiff#80]
Referring to https://github.com/OSGeo/libgeotiff/blob/5d6619c1168845c5bd77686f01e197a82854cbf1/libgeotiff/LICENSE

For the code outside of cmake macros, can we standardize on the exact text of https://spdx.org/licenses/MIT.html ?

The `x style license` text is vague and bit of trouble.

This is also vague and confusing.  Can we make it all MIT?  Folks could then go back in the git history if they want to get to a public domain version.

> All the source code in this toolkit are either in the public domain, or under an X style license.

Thoughts? @warmerdam @rouault 

Also, I don't know Niles D. Ritter.  Do we have current contact info?

cc: @teeler

**Comment by rouault** [comment]
@schwehr He seems to be on https://www.linkedin.com/in/niles-ritter-988975 . I let you contact him if he agrees (and can) relicense his code to MIT.

**Comment by schwehr** [comment]
I've reached out on linked in, but nothing so far.

**Comment by schwehr** [comment]
Going to close this. Can reopen if it becomes critical.
