### ISSUE TITLE
Support button is not placed perfectly in the website

### ISSUE THREAD

**Issue by 456535688765** [OSGeo/libgeotiff#83]
Before
![Screenshot (236)](https://user-images.githubusercontent.com/92295764/224541897-7963fa2c-2f87-45c9-be3b-8e9fb2086346.png)

After  solving the issue
![Screenshot (237)](https://user-images.githubusercontent.com/92295764/224541926-8fd2f509-6ce5-40fb-9146-ccab57140106.png)

**Comment by 456535688765** [comment]
Steps for solving the issue
1. Just have to change the margin of the button

**Comment by 456535688765** [comment]
Should I start with the PR

**Comment by rouault** [comment]
This is the bug tracker of the libgeotiff software, not the OSGeo website. See https://www.osgeo.org/about/contact/

**Comment by 456535688765** [comment]
So this id not an issue Mr @rouault

**Comment by 456535688765** [comment]
I got it
