### ISSUE TITLE
libgeotiff 1.7.0 - No libgeotiff.so.5 file after running make install

### ISSUE THREAD

**Issue by kmilo9999** [OSGeo/libgeotiff#87]
Hello,

I am building/compiling on a linux redhat machine using cmake 3.20. 
After running `make install` , I only see` lib/libgeotiff.a` , but I dont see the shader object `libgeotiff.so`.

Any thoughts on what am I missing in the build process?

Thanks

**Comment by rouault** [comment]
likely -DBUILD_SHARED_LIBS=ON
